"""Tag repository port."""

from __future__ import annotations

from typing import Protocol, runtime_checkable

from archub_cms.domain.tags.tag import Tag, TagNode


@runtime_checkable
class TagRepository(Protocol):
    def get(self, slug: str) -> Tag | None: ...
    def list_all(self) -> list[Tag]: ...
    def tree(self) -> list[TagNode]: ...
    def upsert(self, tag: Tag) -> Tag: ...
    def delete(self, slug: str) -> bool: ...
    def find_by_alias(self, alias: str) -> Tag | None: ...
