"""Bookmark repository port."""

from __future__ import annotations

from typing import Protocol, runtime_checkable

from archub_cms.domain.bookmarks.bookmark import Bookmark, BookmarkFolder


@runtime_checkable
class BookmarkRepository(Protocol):
    def add(self, bookmark: Bookmark) -> Bookmark: ...
    def remove(self, bookmark_id: str) -> bool: ...
    def list_for_user(self, username: str, *, folder_id: str = "") -> list[Bookmark]: ...
    def get(self, bookmark_id: str) -> Bookmark | None: ...
    def find(self, username: str, node_id: str) -> Bookmark | None: ...
    def folders(self, username: str) -> list[BookmarkFolder]: ...
    def create_folder(self, folder: BookmarkFolder) -> BookmarkFolder: ...
    def delete_folder(self, folder_id: str) -> bool: ...
